### ISSUE TITLE
DiamondValley / DevWeekend 2018 / 2018-01-19 a 2018-01-21

### ISSUE THREAD

**Issue by pabloolvcastro** [minasdev/eventos#21]
- Evento: [DevWeekend 2018](http://devweekend.com.br/)
- Local: [Colégio Diamantinense/Diamantina](https://goo.gl/maps/A4sc5cPbgt82)
- Data: 2018-01-19 a 2018-01-21
- Descrição: O maior evento de TI e Empreendedorismo de Diamantina e região. O evento leva aos developers do interior de Minas uma oportunidade unica para saber mais sobre suas carreiras, fazer networking e aprender mais sobre empreendedorismo e algumas paths técnicas.
- Comunidade: DiamondValley

**Comment by obetomuniz** [comment]
Assim que for incluido na listagem do [https://minasdev.org](https://minasdev.org) iremos fechar essa issue. O irá aparecer no site em no máximo um dia após o fechamento da issue.
