### ISSUE TITLE
Dev Talks PUC Minas #01 / 2019-02-12

### ISSUE THREAD

**Issue by solutweb** [minasdev/eventos#28]
- Evento: [Dev Talks PUC Minas #01](https://www.sympla.com.br/dev-talks-puc-minas-01__450708/)
- Local: [PUC Minas Praça da Liberdade](https://goo.gl/maps/iSXZXWiPi9n)
- Data: 2019-02-12
- Descrição: Os participantes estão sendo definidos. Teremos duas mesas redondas com os seguintes temas: "Arquitetura baseada em eventos" e "Frameworks de Front End".

**Comment by solutweb** [comment]
@obetomuniz o evento vai automaticamente ou tem que ser aprovado?

**Comment by obetomuniz** [comment]
Vai ser inserido hoje ainda :) Valeu @solutweb

**Comment by obetomuniz** [comment]
Na verdade, nem precisa publicar mais, irei adicionar o link do grupo especifico do meetup, e este, tal como, futuros eventos irão aparecer no site do Minas Dev

**Comment by solutweb** [comment]
Legal!

Acabei de atualizar o link do evento pois eles estão com a inscrição pelo Sympla.
