### ISSUE TITLE
JS Tech Talk: Mapa de aprendizado Front-End por Caio Vaccaro / 2019-02-13

### ISSUE THREAD

**Issue by solutweb** [minasdev/eventos#29]
- Evento: [JS Tech Talk: Mapa de aprendizado Front-End por Caio Vaccaro](https://www.meetup.com/pt-BR/Beaga-JS/events/257901488/)
- Local: [AppProva](https://www.google.com/maps/search/?api=1&query=-19.935223%2C-43.925663)
- Data: 2019-02-13
- Descrição: Nessa conversa, Caio tentará passar um pouco do seu conhecimento adquirido em sua carreira. Interagir com diferentes profissionais, participar de diferentes projetos e também mesclando a vida pessoal e profissional, aprendeu uma perspectiva diferente do que é ser desenvolvedor Front-End e o conhecimento necessário para tal.

**Comment by obetomuniz** [comment]
Adicionado 👍
