### ISSUE TITLE
Gestão de projetos em massa: lições, lidar com times com projetos simultâneos

### ISSUE THREAD

**Issue by alvaro4ugusto** [minasdev/eventos#30]
- Evento: [Gestão de projetos em massa: lições, lidar com times com projetos simultâneos
](https://www.meetup.com/pt-BR/GDG-BH/events/258934115/?isFirstPublish=true)
- Local: [Rock Content](https://goo.gl/maps/wLQ75pCMQ7A2)
- Data: 26/02/2019, 19:00 até 21:30
- Descrição: Quero falar um pouco sobre o que aprendi ao assumir um time que gerencia mais de 100 projetos simultâneos. Esses conhecimentos vão desde noções técnicas sobre gestão de projetos até a criação de processos e critérios de avaliação de sucesso do projeto. Tudo isso muito personalizado e com pouquíssimos benchmarks: ninguém no mundo faz o que fazemos!

Vamos juntos? Te espero lá!
- Comunidade: GDG - Women techmakers

**Comment by obetomuniz** [comment]
Obrigado por contribuir. Já está sendo listado no minasdev.org
