### ISSUE TITLE
Introdução ao Teste de APIs com JMeter

### ISSUE THREAD

**Issue by brunopulis** [minasdev/eventos#38]
- Evento: [Introdução ao Teste de APIs com JMeter](https://www.meetup.com/pt-BR/Testing-Dojo-Uai/events/265475769/)
- Local: [Maio Marketing](https://www.google.com/maps/search/?api=1&query=Rua+Sergipe%2C+1014%2C+8%C2%BA+andar%2C+Funcion%C3%A1rios%2C+Belo+Horizonte%2C+Belo+Horizonte%2C+BR)
- Data: 2019-10-16
- Descrição: Introdução a testes de API utilizando a ferramenta JMeter.
- Comunidade: Testing Dojo UAI

**Comment by obetomuniz** [comment]
Valeu por compartilhar @brunopulis 

O meetup `Testing-Dojo-Uai` e eventos do mesmo já estão cadastrados. Logo todos os eventos dele irão aparecer no minasdev.org.
