### ISSUE TITLE
Hubcon 2

### ISSUE THREAD

**Issue by igorcaldeira** [minasdev/eventos#40]
- Evento: [Hubcon² (segunda edição)](https://hubcon.org)
- Local: [UNA Aimorés](https://www.google.com/maps/place/Una+Aimor%C3%A9s/@-19.9286235,-43.9378725,15z/data=!4m2!3m1!1s0x0:0x8e93c8bbee592e76?sa=X&ved=2ahUKEwjXz7qg5ZblAhWTILkGHRHBCLEQ_BIwE3oECAsQCA)
- Data: 2019-12-07
- Descrição: A hubcon é um evento de desenvolvimento e tecnologia que não se limita a um tema ou área, trazendo um dia incrível de evento com vários especialistas da comunidade.
- Comunidade: Hubcon

**Comment by obetomuniz** [comment]
✅ Done
